db:
  url: jdbc:postgresql://localhost:5432/SEMESTER
  username: postgres
  password: terenin79
  hikari:
    max-pool-size: 10
  driver:
    classname: org.postgresql.Driver

spring:
  security:
    jwt:
      secret: 3eb5dee7de954d6ca9a0c6d9219f35c6

rabbit:
  username: guest
  password: guest